In [ ]:
!pip install tensorflow

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
#vocab_size

voc_size=500

# One Hot Representation

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[347, 322, 137, 315], [347, 322, 137, 188], [347, 162, 137, 138], [449, 242, 158, 336, 245], [449, 242, 158, 336, 126], [445, 347, 79, 137, 363], [279, 223, 9, 336]]


# Word Embedding Representation

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np


# Padding for making the size of all the Vectors same

In [ ]:
dim=10

In [ ]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 347 322 137 315]
 [  0   0   0   0 347 322 137 188]
 [  0   0   0   0 347 162 137 138]
 [  0   0   0 449 242 158 336 245]
 [  0   0   0 449 242 158 336 126]
 [  0   0   0 445 347  79 137 363]
 [  0   0   0   0 279 223   9 336]]


# Converting to Vectors

In [ ]:

model = Sequential()
model.add(
    Embedding(
        input_dim=voc_size,
        output_dim=10,
        input_length=sent_length,
        input_shape=(sent_length,)
    )
)
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (None, 8, 10)          │         5,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
embedded_docs[0]

array([  0,   0,   0,   0, 347, 322, 137, 315], dtype=int32)

In [ ]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 304ms/step


array([[[ 0.0253771 ,  0.03646685, -0.00678084, -0.00284993,
          0.0323129 ,  0.00819267,  0.03800677, -0.03478398,
         -0.04267962,  0.04977653],
        [ 0.0253771 ,  0.03646685, -0.00678084, -0.00284993,
          0.0323129 ,  0.00819267,  0.03800677, -0.03478398,
         -0.04267962,  0.04977653],
        [ 0.0253771 ,  0.03646685, -0.00678084, -0.00284993,
          0.0323129 ,  0.00819267,  0.03800677, -0.03478398,
         -0.04267962,  0.04977653],
        [ 0.0253771 ,  0.03646685, -0.00678084, -0.00284993,
          0.0323129 ,  0.00819267,  0.03800677, -0.03478398,
         -0.04267962,  0.04977653],
        [-0.04847788, -0.01362167, -0.03890365,  0.03077606,
         -0.04633803, -0.04866531, -0.02581364,  0.03229685,
         -0.02115152, -0.01286403],
        [-0.04350303, -0.00510705,  0.03038012,  0.03628292,
          0.02042885, -0.01014601, -0.04564443, -0.01756625,
          0.04646213, -0.04683298],
        [-0.04860986,  0.0347185 ,  0.00856156, -0.0